apiVersion: v1
kind: Pod
metadata:
  name: nginx-devsecops
  labels:
    team: devsecops
    app: todo
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      resources:
        requests:
          memory: 100Mi
        limits:
          memory: 200Mi
          cpu: "1"
